### ISSUE TITLE
support for email backend without auth (maildev)

### ISSUE THREAD

**Issue by ondrejsika** [sikalabs/tergum#21]
```
Notification:
  Backend:
    Email:
      SmtpHost: 127.0.0.1
      SmtpPort: 11025
      Username: null
      Password: null
      From: tergum@example.com
```

```
EmailBackend backend requires Username
```
